SUCCESSFUL_VERBIAGE = [
    "malfunction",
    "Bleeding the cooling system was successful",
    "The basic setting of the bleeding routine was completed.",
    "The test - Bleeding the low-temperature circuit was successfully ended.",
    "The pistons are put back",
    "The pistons are put forward",
    "The basic setting has been performed successfully",
    "The re-initialization function has been performed successfully.",
    "The correction function has been performed successfully.",
    "The adaptation has been completed successfully",
    "The crankshaft correction values stored in the engine control module are: OK",
    "The camshaft correction values stored in the engine control module are: OK",
    "The basic setting has been performed successfully. Resetting of injector adaptation values",
    "Adaptation value successfully reset",
    "Bleeding ended!",
    "The adaptation was performed correctly",
    "The sensor wheel adaptation values were reset",
    "The adaptation of the following component was successful: Charge Air Pressure Actuator - V465",
    "The adjustment of the component is completed",
    "Adaption of oxygen sensor learnt values not necessary or Adaption of oxygen sensor learnt values necessary",
    "Status of readiness code: OK",
    "the basic setting is",
    "Adaptation OK",
    "Top up ATF or Install the ATF check and fill plug with a new seal in the ATF pan",
    "Install the ATF check and fill plug with a new seal in the ATF pan",
    "The Throttle Valve Control Module -J338- has been adapted to the Engine Control Module (ECM)",
    "The adaptation of Engine Temperature Control Actuator - N493 was successful",
    "The Engine Temperature Control Actuator -N493- is adapted to the engine control module."
]
